### ISSUE TITLE
Will there be updates on the unit tests in test_gcm.pu

### ISSUE THREAD

**Issue by heng2j** [smorad/graph-conv-memory#1]
Hi Team,

First of all great work and fascinating paper! And my team is trying to see if it is feasible to leverage GCM in our project.  I see some recent changes and updates to further cleanup and improve GCM. Greatly appreciate your continuous development.

I have questions on the unit tests. Current the tests are broken due to the recent refactoring. Any plan for updating the tests?

Thank you,
Heng

**Comment by smorad** [comment]
Hi,

The tests should be updated in a week or so, after the ICLR submission deadline. Everything should still be working at the moment, however! I think most of the failed tests are for the `BernoulliEdge`, which is a new feature I'm working on (and not yet mentioned in the README).

**Comment by smorad** [comment]
I fixed the broken import that caused all tests to fail in https://github.com/smorad/graph-conv-memory/commit/4553318ffdf531d6ed1861a42d91078ada4809b3. Now, at least you can see which tests are failing. The failure for distance and temporal edges is not important. They will be fixed soon.

**Comment by heng2j** [comment]
Thanks to @smorad's help on this issue https://github.com/smorad/graph-conv-memory-paper/issues/1, I believe we are on track to have working unit tests. 

All the best for  the ICLR submission!

Cheers!
